//----------------------------------------------------------------------------
// File:	genclut.c
// Author:	evilo
// Notes:	generate a lookup table to convert RGB565 to RGBA8888.
//----------------------------------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

//----------------------------------------------------------------------------
#ifdef WIN32
#pragma pack(push)
#pragma pack(1)
#endif


#ifdef WIN32
#pragma pack(pop)
#endif


//----------------------------------------------------------------------------
int main(int argc, char **argv)
{
	unsigned int r,g,b;
	unsigned int fd,cp;

	fprintf(stdout, "// File Generated by genclut \n", filename);
	fprintf(stdout,"#ifndef _CLUT_H\n");
	fprintf(stdout,"#define _CLUT_H\n\n\n");
	
	fprintf(stdout, "static const uint32 CLUT[65536] = { ");

			
	for (fd=0;fd<0xFFFF;fd++)
	{
	
	  r = (((fd >> 11) & 0x001F) * 0xFF) / 0x1F; 
	  g = (((fd >> 5) & 0x003F) * 0xFF) / 0x3F; 
	  b = ((fd & 0x1f) * 0xFF)  / 0x1F;
						
	  fprintf (stdout, "0x80%x, ",(unsigned int)(r|g <<8|b <<16));
	  
	  
	  cp++;
	  // yes, this is not nice, but who cares...
	  if (cp==8)  
	  {
	  	fprintf (stdout,"\n");
	  	cp=0;
	  }
	}
	
	// last one FFFFFF
	fprintf (stdout, "0x80ffffff");
	fprintf(stdout, "} __attribute__((aligned(64)));\n\n");
	fprintf(stdout,"#endif\n");

	return(0);
}

